version: '3'

services:
  web:
    image: nginx:1.19
    container_name: symfony
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - .:/app
    ports:
      - 90:80
    restart: always
    depends_on:
      - php
  php:
    build:
      context: ./
      dockerfile: ./docker/php/Dockerfile
    container_name: symfony-php
    restart: always
    volumes:
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini
      - .:/app
  postgres:
    image: postgres:13.2
    container_name: symfony-psql
    restart: always
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./var/postgresql:/var/lib/postgresql/data:z
    ports:
      - 5439:5432
  mongodb:
    image: mongo:4.4.4
    container_name: symfony-mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_NAME}
    volumes:
      - ./var/mongodb-data:/data/db:z
    ports:
      - 27010:27017
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo 10.10.10.60:27017/test --quiet
      interval: 30s
      timeout: 10s
      retries: 3
    restart: always
